services:
  - type: web
    name: social-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://social-network-backend-9gdm.onrender.com
      - key: VITE_FRONTEND_URL
        value: https://social-network-fronted.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
